# Generated by Django 5.1.6 on 2025-02-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=202)),
                ('image', models.FileField(upload_to='about/')),
                ('description', models.TextField()),
                ('birthday', models.IntegerField()),
                ('location', models.CharField(max_length=202)),
                ('email', models.CharField(max_length=202)),
                ('phone', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
